excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://janwillemaikens.github.io
name: Jan-Willems's gedachten
description: Kijk mee in mijn hoofd... misschien begrijp je er meer van dan ik.
author: Jan-Willem
avatar: http://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 